using JeDax.Data;
using JeDax.Security;
using JeDax.Services;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();

builder.Services.AddScoped<TenantContext>();

bool usePostgres = builder.Configuration.GetValue<bool>("UsePostgres");

if (usePostgres)
{
    var cs = string.Format("Host={0};Port={1};Database={2};Username={3};Password={4}",
        Environment.GetEnvironmentVariable("PGHOST"),
        Environment.GetEnvironmentVariable("PGPORT"),
        Environment.GetEnvironmentVariable("PGDATABASE"),
        Environment.GetEnvironmentVariable("PGUSER"),
        Environment.GetEnvironmentVariable("PGPASSWORD"));
    builder.Services.AddDbContext<AppDbContext>(opt => opt
        .UseNpgsql(cs)
        .ConfigureWarnings(w => w.Ignore(RelationalEventId.PendingModelChangesWarning)));
}
else
{
    var connectionString = builder.Configuration.GetConnectionString("Default");
    builder.Services.AddDbContext<AppDbContext>(opt =>
        opt.UseSqlite(connectionString ?? "Data Source=jedax_dev.db"));
}

builder.Services.AddDataProtection()
    .PersistKeysToDbContext<AppDbContext>();

builder.Services.AddScoped<AuthService>();
builder.Services.AddScoped<InventarioService>();
builder.Services.AddScoped<ValeService>();
builder.Services.AddScoped<ExportService>();
builder.Services.AddScoped<UsuarioService>();
builder.Services.AddScoped<CaseGeneradorService>();
builder.Services.AddScoped<UserSession>();
builder.Services.AddScoped<ValeImportService>();

var app = builder.Build();

// Always run migrations. Seed only in Development.
{
    using var scope = app.Services.CreateScope();
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    await db.Database.MigrateAsync();

    if (usePostgres)
    {
        // Fix DataProtectionKeys.Id → IDENTITY (migración generada con SQLite)
        await db.Database.ExecuteSqlRawAsync(@"
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'DataProtectionKeys'
                      AND column_name = 'Id'
                      AND is_identity = 'YES'
                ) THEN
                    DROP TABLE IF EXISTS ""DataProtectionKeys"";
                    CREATE TABLE ""DataProtectionKeys"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""FriendlyName"" text,
                        ""Xml"" text,
                        CONSTRAINT ""PK_DataProtectionKeys"" PRIMARY KEY (""Id"")
                    );
                END IF;
            END $$;
        ");

        // Fix Id → IDENTITY en todas las tablas (migraciones SQLite usan Sqlite:Autoincrement)
        await db.Database.ExecuteSqlRawAsync(@"
            DO $$
            DECLARE tbl text;
            BEGIN
                FOREACH tbl IN ARRAY ARRAY['Tenants','Usuarios','Productos','Cases','Vales','ValeDetalles','Movimientos','DataProtectionKeys']
                LOOP
                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = tbl)
                    AND NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = tbl AND column_name = 'Id' AND is_identity = 'YES'
                    ) THEN
                        EXECUTE format('ALTER TABLE %I ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY', tbl);
                    END IF;
                END LOOP;
            END $$;
        ");

        // Fix columnas bool → type boolean (migradas como INTEGER desde SQLite)
        await db.Database.ExecuteSqlRawAsync(@"
            DO $$
            BEGIN
                IF (SELECT data_type FROM information_schema.columns
                    WHERE table_name='Tenants' AND column_name='Activo') = 'integer' THEN
                    ALTER TABLE ""Tenants""      ALTER COLUMN ""Activo""    DROP DEFAULT;
                    ALTER TABLE ""Tenants""      ALTER COLUMN ""Activo""    TYPE boolean USING ""Activo""::boolean;
                    ALTER TABLE ""Tenants""      ALTER COLUMN ""Activo""    SET DEFAULT false;

                    ALTER TABLE ""Usuarios""     ALTER COLUMN ""Activo""    DROP DEFAULT;
                    ALTER TABLE ""Usuarios""     ALTER COLUMN ""Activo""    TYPE boolean USING ""Activo""::boolean;
                    ALTER TABLE ""Usuarios""     ALTER COLUMN ""Activo""    SET DEFAULT false;

                    ALTER TABLE ""Productos""    ALTER COLUMN ""Activo""    DROP DEFAULT;
                    ALTER TABLE ""Productos""    ALTER COLUMN ""Activo""    TYPE boolean USING ""Activo""::boolean;
                    ALTER TABLE ""Productos""    ALTER COLUMN ""Activo""    SET DEFAULT false;

                    ALTER TABLE ""ValeDetalles"" ALTER COLUMN ""Procesado"" DROP DEFAULT;
                    ALTER TABLE ""ValeDetalles"" ALTER COLUMN ""Procesado"" TYPE boolean USING ""Procesado""::boolean;
                    ALTER TABLE ""ValeDetalles"" ALTER COLUMN ""Procesado"" SET DEFAULT false;
                END IF;
            END $$;
        ");

        // Fix columnas DateTime → type timestamp (migradas como TEXT desde SQLite)
        await db.Database.ExecuteSqlRawAsync(@"
            DO $$
            BEGIN
                IF (SELECT data_type FROM information_schema.columns
                    WHERE table_name='Tenants' AND column_name='CreadoEn') = 'text' THEN
                    ALTER TABLE ""Tenants""      ALTER COLUMN ""CreadoEn""       TYPE timestamp USING ""CreadoEn""::timestamp;
                    ALTER TABLE ""Usuarios""     ALTER COLUMN ""CreadoEn""       TYPE timestamp USING ""CreadoEn""::timestamp;
                    ALTER TABLE ""Vales""        ALTER COLUMN ""FechaCreacion""  TYPE timestamp USING ""FechaCreacion""::timestamp;
                    ALTER TABLE ""Cases""        ALTER COLUMN ""FechaRegistro""  TYPE timestamp USING ""FechaRegistro""::timestamp;
                    ALTER TABLE ""Cases""        ALTER COLUMN ""FechaUbicacion"" TYPE timestamp USING ""FechaUbicacion""::timestamp;
                    ALTER TABLE ""Cases""        ALTER COLUMN ""FechaSalida""    TYPE timestamp USING ""FechaSalida""::timestamp;
                    ALTER TABLE ""Movimientos""  ALTER COLUMN ""Fecha""          TYPE timestamp USING ""Fecha""::timestamp;
                    ALTER TABLE ""ValeDetalles"" ALTER COLUMN ""FechaProcesado"" TYPE timestamp USING ""FechaProcesado""::timestamp;
                END IF;
            END $$;
        ");
    }

    await JeDax.Data.DbSeeder.SeedAsync(db);
}

app.UseForwardedHeaders(new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
});

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    app.UseHsts();
}

if (app.Environment.IsDevelopment())
    app.UseHttpsRedirection();
app.UseStaticFiles();

app.MapGet("/health", () => "JeDax OK");
app.MapGet("/", () => Results.Redirect("/login"));

app.MapBlazorHub();
app.MapRazorComponents<JeDax.Components.App>()
    .AddInteractiveServerRenderMode()
    .DisableAntiforgery();

app.Run();
