using JeDax.Data;
using JeDax.Security;
using JeDax.Services;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();

builder.Services.AddScoped<TenantContext>();

bool usePostgres = builder.Configuration.GetValue<bool>("UsePostgres");

if (usePostgres)
{
    var cs = string.Format("Host={0};Port={1};Database={2};Username={3};Password={4}",
        Environment.GetEnvironmentVariable("PGHOST"),
        Environment.GetEnvironmentVariable("PGPORT"),
        Environment.GetEnvironmentVariable("PGDATABASE"),
        Environment.GetEnvironmentVariable("PGUSER"),
        Environment.GetEnvironmentVariable("PGPASSWORD"));
    builder.Services.AddDbContext<AppDbContext>(opt => opt
        .UseNpgsql(cs)
        .ConfigureWarnings(w => w.Ignore(RelationalEventId.PendingModelChangesWarning)));
}
else
{
    var connectionString = builder.Configuration.GetConnectionString("Default");
    builder.Services.AddDbContext<AppDbContext>(opt =>
        opt.UseSqlite(connectionString ?? "Data Source=jedax_dev.db"));
}

builder.Services.AddDataProtection()
    .PersistKeysToDbContext<AppDbContext>();

builder.Services.AddScoped<AuthService>();
builder.Services.AddScoped<InventarioService>();
builder.Services.AddScoped<ValeService>();
builder.Services.AddScoped<ExportService>();
builder.Services.AddScoped<UsuarioService>();
builder.Services.AddScoped<CaseGeneradorService>();
builder.Services.AddScoped<UserSession>();
builder.Services.AddScoped<ValeImportService>();

var app = builder.Build();

// Always run migrations. Seed only in Development.
{
    using var scope = app.Services.CreateScope();
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    await db.Database.MigrateAsync();

    // Ensure DataProtectionKeys.Id is an IDENTITY column on PostgreSQL
    // (migration was originally generated with SQLite tooling and lacks identity).
    if (usePostgres)
    {
        await db.Database.ExecuteSqlRawAsync(@"
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'DataProtectionKeys'
                      AND column_name = 'Id'
                      AND is_identity = 'YES'
                ) THEN
                    DROP TABLE IF EXISTS ""DataProtectionKeys"";
                    CREATE TABLE ""DataProtectionKeys"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""FriendlyName"" text,
                        ""Xml"" text,
                        CONSTRAINT ""PK_DataProtectionKeys"" PRIMARY KEY (""Id"")
                    );
                END IF;
            END $$;
        ");
    }

    if (app.Environment.IsDevelopment())
        await JeDax.Data.DbSeeder.SeedAsync(db);
}

app.UseForwardedHeaders(new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
});

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    app.UseHsts();
}

if (app.Environment.IsDevelopment())
    app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseAntiforgery();

app.MapGet("/", () => Results.Redirect("/login"));

app.MapRazorComponents<JeDax.Components.App>()
    .AddInteractiveServerRenderMode();

app.Run();
