using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace JeDax.Migrations
{
    public partial class FixDataProtectionKeysIdentity : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DROP TABLE IF EXISTS ""DataProtectionKeys"";
                CREATE TABLE ""DataProtectionKeys"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""FriendlyName"" text,
                    ""Xml"" text,
                    CONSTRAINT ""PK_DataProtectionKeys"" PRIMARY KEY (""Id"")
                );
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "DataProtectionKeys");
        }
    }
}
